version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    assignees:
      - 'rotyro'
    reviewers:
      - 'rotyro'
    labels:
      - 'dependencies'
      - 'yarn'
      - 'automated'
    commit-message:
      prefix: 'chore(deps): '
    open-pull-requests-limit: 10
